---
title: "R Notebook"
output: html_notebook
---


# 0.0 Imports



```{r}
renv::restore()
```


```{r}
library(tidyverse)
```

```{r}
mpg
```

```{r}
ggplot( mpg, aes(x = displ, y = hwy, color = class)) + 
  geom_point()

ggplot( mpg, aes(x = displ, y = hwy, alpha = class)) +
  geom_point()
  
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(color = "blue")

```

# 1.0 Exercises

```{r}
mpg
```


```{r}
mpg |> ggplot(aes(
  x = displ,
  y = hwy
  )) +
  geom_point(shape = 24, fill="pink", color="blue", size=3)
```

```{r}
ggplot(mpg) +
  geom_point(aes(x = displ, y = hwy), color="blue")

#Because aes mapping maps the behavior of the charts in variables, color argument inside aes gives for each variable a color, since it is a raw string, ever instance gets the same group called "blue".
```


```{r}
mpg
```


```{r}
ggplot(mpg) +
  geom_point( aes( x=displ, y=hwy, color=cty<18) )

# When I use boolean condition in a color map to an aesthetic, the instances which met the conditions get colored from those which didn't.
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth()
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(aes(linetype = drv))
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(aes(color = drv))
```
```{r}
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point(aes(color = class)) +
  geom_smooth()
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_point(
    data = mpg |> filter(class == "2seater"),
    color = "red"
  ) +
  geom_point(
    data = mpg |> filter(class == "2seater"),
    shape= "circle open", size = 3, color = "red")
```


```{r}
ggplot(mpg, aes(x=hwy)) +
  geom_histogram(binwidth = 2)

ggplot(mpg, aes(x = hwy)) +
  geom_density()

ggplot(mpg, aes(x = hwy)) +
  geom_boxplot()
```

```{r}
mpg
```

#2.0 Exercises geometric objects

```{r}
ggplot(mpg, aes(x=displ, y=hwy)) +
  geom_line()

ggplot(mpg, aes(x=displ, y=hwy)) +
  geom_area()


#2)
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(aes(color = drv))

#3)
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(aes(color = drv), se = FALSE)

#4)
ggplot(mpg, aes( x = displ, y = hwy)) +
  geom_smooth() +
  geom_point()

ggplot(mpg, aes( x = displ, y = hwy)) +
  geom_smooth( aes(group = drv)) +
  geom_point()

ggplot(mpg, aes( x = displ, y = hwy, color=drv)) +
  geom_smooth() +
  geom_point()

ggplot(mpg, aes( x = displ, y = hwy)) +
  geom_smooth( se = FALSE) +
  geom_point( aes(color = drv) )

ggplot(mpg, aes( x = displ, y = hwy)) +
  geom_smooth( aes(linetype = drv), show.legend = FALSE) +
  geom_point( aes(color = drv) )

ggplot(mpg, aes( x = displ, y = hwy)) +
  geom_point(colour = "white", size = 4) +
    geom_point( aes(color = drv), size = 2)

```

# 3.0 Facets

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_grid(drv ~ cyl, scales = "free_x")
```

```{r}
#2)
ggplot(mpg) +
  geom_point(aes(x = drv, y = cyl))

#3)
ggplot(mpg) +
  geom_point(aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)

ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)

#4)
ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) +
  facet_wrap(~ class, nrow = 2)

#5)
ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) +
  facet_wrap(~ class, nrow = 2, shrink = FALSE, strip.position = "top")

ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) +
  facet_grid(. ~ class)
#It doesn't have ncol or nrow because this is already pre-defined by cardinality of the mapping variable.

#6) The first one it's much better to make easier to compare engine size across cars, It depends on the axis of the value variable you are comparing, it needs to be in the same axis
ggplot(mpg, aes(x = displ)) +
  geom_histogram() +
  facet_grid(drv ~ .)

ggplot(mpg, aes(x = displ)) +
  geom_histogram() +
  facet_grid(. ~ drv)

#7) In facet grid the first argument is row faceting variable, whereas in facet_wrap it its columns's.
ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)

ggplot(mpg) + 
  geom_point(aes(x = displ, y = hwy)) +
  facet_wrap(drv ~ .)

```

# 4.0 Statistical Transformation

```{r}
diamonds |> 
  count(cut) |> 
  ggplot(aes(x = cut, y = n)) +
  geom_bar(stat = "identity")
```

```{r}
diamonds |> 
  ggplot(aes(x=cut)) +
  geom_bar(stat="identity")
```

