---
title: "R Notebook"
output: html_notebook
---


# 0.0 Imports

```{r}
renv::snapshot()
```

```{r}
options(scipen = 999)
options(digits = 6)
```


```{r}
library(tidyverse)
library(babynames)
```

# 1.0 Creating a String

```{r}
single_quote <- '\''
double_quote <- "\""
backslash <- "\\"

x <- c(single_quote, double_quote, backslash)
x

str_view(x)
```

```{r}
?Quotes
```

## 1.1 Exercises

```{r}
str_view("\\a\\b\\c\\d")

str_view("\\\\\\\\\\\\")

str_view("This is \u00a0 is \U0001f604")

```


# 2.0 Creating Many Strings from Data


```{r}
str_c("x", "y")

str_c("Hello ", c("John", "Susan"), NA)

paste0("Hello ", c("John", "Susan"), NA)


```

```{r}
df <- tibble(name = c("Flora", "David", "Terra", NA))
df |> mutate(greeting = paste0("Hi ", name, "!"),
             greet = str_c("Hi ", name, "!"),
             greeting1 = str_c("Hi ", coalesce(name, "you"), "!"),
             greeting2 = coalesce(str_c("Hi ", name, "!"), "Hi!"))
```

```{r}
df |> mutate(
             greeting1 = str_c("Hi ", coalesce(name, "you"), "!"),
             greeting2 = coalesce(str_c("Hi ", name, "!"), "Hi!"))
```




```{r}
df |> mutate(greeting4 = str_glue("Hi {name}!"),
             greeting5 = str_glue("{{Hi {name}!}}"))
```

```{r}
df <- tribble(
~ name, ~ fruit,
"Carmen", "banana",
"Carmen", "apple",
"Marvin", "nectarine",
"Terence", "cantaloupe",
"Terence", "papaya",
"Terence", "mandarin"
)

df
```
```{r}
df |> 
  group_by(name) |> 
  summarize(fruits = str_flatten(fruit, ", "))
```

# 2.1 Exercises

```{r}
#1)
str_c("hi ", NA)
str_c(letters[1:2], letters[1:3])

paste0("hi ", NA)
paste0(letters[1:2], letters[1:5])


# str_c has recyclue rules, which if a vector has size 1, it is repeated to match the other's size, also, str_c print NA for the entire output if there is at least one NA. Whereas paste0 print NA as a string and repeate the lowest element to match the other repeating.

```
```{r}

#2)
paste("quem foi", "passou", "mao")

str_c("quem foi", "passou", "mao", sep = " ")
```

```{r}

#3)
food <- "Abacate"
age <- 27
country <- "Brazil"
price <- 3

str_c("The price of ", food, " is ", price)

str_glue("The price of {food} is {price}")


```

```{r}
str_glue("I'm {age} years old and live in {country}")

str_c("I'm", age, "years old and live in", country, sep=" ")
```

```{r}
title <- "robobou"
str_c("\\section{", title, "}")


str_glue("\\\\section{{", {title}, "}}")


```

# 3.0 Extracting Data from Strings

```{r}
df1 <- tibble(x = c("a,b,c", "d,e", "f"))
df1
```

```{r}
df1 |> separate_longer_delim(x, delim = ",")
```


```{r}
df3 <- tibble(x = c("a10.1.2022", "b10.2.2011", "e15.1.2015"))
df3
df3 |> 
  separate_wider_delim(
    x,
    delim = ".",
    names = c("code", "edition", "year")
  )
df3 |> 
  separate_wider_delim(
    x,
    delim = ".",
    names = c("code", NA, "year")
  )
```


```{r}
df4 <- tibble(x = c("202215TX", "202122LA", "202325CA"))
df4 |>
  separate_wider_position(
    x,
    widths = c(year = 4, age = 2, state = 2)
  )
```


```{r}
df <- tibble(x = c("1-1-1", "1-1-2", "1-3", "1-3-2", "1"))
df
```

```{r}
debug <- df |> 
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_few = "debug"
  )
debug
```

```{r}
debug |> filter(!x_ok)
```

```{r}
df |> 
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_few = "align_start"
  )
```

```{r}
df <- tibble(x = c("1-1-1", "1-1-2", "1-3-5-6", "1-3-2", "1-3-5-7-9"))

df |> 
  separate_wider_delim(
    x,
    delim = "-",
    names = c("x", "y", "z"),
    too_many = "debug"
  )

```

# 3.0 Letters


```{r}
str_length(c("a", "R for data science", NA))
```

```{r}
head(babynames)
```

```{r}
babynames |> 
  count(length = str_length(name), wt = n)
```

```{r}
babynames |> 
  filter(str_length(name) == 15) |> 
  count(name , wt = n, sort = TRUE)
```

```{r}
x <- c("Apple", "Banana", "Pear")

str_sub(x, 1 ,3)
```


```{r}
str_sub(x, -3, -1)
```

```{r}
str_sub("a", 1, 5)
```

```{r}
babynames |> 
  mutate(
    first = str_sub(name, 1, 1),
    last = str_sub(name, -1, -1)
  )
```

## 3.1 Exercises

```{r}
#1)
# Because babynames is already grouped and N represents the sum of the babies with the name, If we wouldn't use it, it would show a lesser quantity than it actually is.

#2)
babynames |> 
  mutate(
    middle_letter = str_sub(name, ceiling(str_length(name)/2), ceiling(str_length(name)/2))
  )

#3)
ex3 <- babynames |> 
  mutate(
    len = as.factor(str_length(name)),
    first_letter = as.factor(str_sub(name,1,1)),
    last_letter = as.factor(str_sub(name,-1))
    )


ex3 |> summarize(
    sum_names = sum(n),
    .by = c(len, year)
    ) |> 
  arrange(len) |> ggplot(aes(x = year, y = sum_names, color = len)) +
  geom_line()




ex3 |> summarize(
    sum_names = sum(n),
    .by = c(first_letter, year)
    ) |> 
  arrange(first_letter) |> 
  ggplot(aes(x = year, y = sum_names, color = first_letter)) +
  geom_line()


ex3 |> summarize(
    sum_names = sum(n),
    .by = c(last_letter, year)
    ) |> 
  arrange(last_letter) |> 
  ggplot(aes(x = year, y = sum_names, color = last_letter)) +
  geom_line()

```


# 4.0 Non-English Text

```{r}
charToRaw("Hadley")
```


```{r}
x1 <- "text\nEl Ni\xf1o was particularly bad this year"
read_csv(x1)
read_csv(x1, locale = locale(encoding = "Latin1"))
```

```{r}
x2 <- "text\n\x82\xb1\x82\xf1\x82\xc9\x82\xbf\x82\xcd"
read_csv(x2)
read_csv(x2, locale = locale(encoding = "Shift-JIS"))
```

```{r}
guess_encoding(read_csv(x1))
read_csv(x1, locale = locale(encoding = "ISO-8859-1"))
```

```{r}
u <- c("\u00fc", "u\u0308")
u
str_view(u)
```

```{r}
str_length(u)

str_sub(u, 1 ,1)
```

```{r}
u[[1]] == u[[2]]

str_equal(u[[1]], u[[2]])
```

```{r}

paste("aaa","","bbb","","ccc", recycle0 = FALSE)
```


