---
title: "R Notebook"
output: html_notebook
---


# 0.0 Imports

```{r}
renv::snapshot()
```

```{r}
options(scipen=999)
```


```{r}
library(tidyverse)
library(nycflights13)
library(tibble)
```

#1.0 Comparison

```{r}
x <- c(1, 2, 5, 7, 11, 13)
x*2
```
```{r}
df <- tibble(x)
df |> 
  mutate(y = x * 2)

flights |> 
  filter(dep_time >600 & dep_time < 2000 & abs(arr_delay) < 20)


#create conditional columns with mutate
flights |> 
  mutate(
    daytime = dep_time > 600 & dep_time < 2000,
    approx_ontime = abs(arr_delay) < 20,
    .keep = "used"
  )


#to filter and boolean column the TRUE already filter itsel
flights |> 
  mutate(
    daytime = dep_time > 600 & dep_time < 2000,
    approx_ontime = abs(arr_delay) < 20,
  ) |> 
  filter(daytime & approx_ontime)

```

```{r}
x <- c(1 / 49 * 49, sqrt(2)^2)
x

x == c(1,2)
```

```{r}
print(x[1], digits = 16)
```


```{r}
near(x, c(1, 2))
```

```{r}
flights |> 
  filter(dep_time == NA)
```

```{r}
flights |> 
  filter(is.na(dep_time)) |> 
  arrange(dep_time)

flights |> 
  filter(month == 1, day == 1) |> 
  arrange(desc(is.na(dep_time)), dep_time)
```
## 1.1 Exercises

```{r}

##to inhect function argument in data masked context, just embrance it with {{}}
#my_mean <- function(data, var1, var2) {
#  dplyr::summarise(data, mean({{ var1 }} + {{ var2 }}))
#}


#1) near
near(sqrt(2)^2,2)

#2) Não consegui
flights |> 
  mutate(nulo_dep_time = is.na(dep_time)
         ,nulo_sched_dep_time = is.na(sched_dep_time)
         ,nulo_dep_delay = is.na(dep_delay)) |> 
  count(c(nulo_dep_time))

```
# 2.0 Boolean Algebra

```{r}
df <- tibble(x = c(TRUE, FALSE, NA))
df |> 
  mutate(
    and = x & NA,
    or = x | NA
  )
```

```{r}
flights |> 
  filter(month == 11 | month == 12)
```

```{r}
flights |> 
  filter(month == 11 | 12)
```
```{r}
flights |> 
  filter(arr_delay > 0) |> 
  summarize(
    behind = mean(arr_delay),
    n = n(),
    .by = c(year, month, day)
  )
```
```{r}
flights |> 
  summarize(
    behind = mean(arr_delay[arr_delay > 0], na.rm=TRUE),
    ahead = mean(arr_delay[arr_delay < 0], na.rm=TRUE),
    .by = c(year, month, day)
  )
```

```{r}
x <- c(-3:3, NA)
x
if_else(x > 0, "+ve", "-ve")
if_else(x > 0, "+ve", "-ve","esse cara é NA")
```

```{r}
if_else(x > 0, -x, -x)
```

```{r}
x <- c(-3:3, NA, "qiemm", "hulk")
case_when(
  x == 0 ~ "0",
  x < 0 ~ "-ve",
  x > 0 ~ "+ve",
  TRUE ~ "fufu"
)



```

```{r}
#ONLY THE FIRST CONDITION WILL BE MATCHED

case_when(
  x > 0 ~ "+ve",
  x > 2 ~ "big"
)
```

```{r}
flights |> 
  mutate(
    status = case_when(
      is.na(arr_delay) ~ "cancelled",
      arr_delay < -30 ~ "very early",
      arr_delay < -15 ~ "early",
      abs(arr_delay) <= 15 ~"on time",
      arr_delay < 60 ~ "late",
      arr_delay < Inf ~ "very late",
    ),
    .keep = "used"
  ) |> count(status)
```

## 2.1 Exercises

```{r}
head(flights)
```


```{r}
#1)
fli <- flights |> 
  mutate(miss = (arr_delay %in% c(NA)) & !(dep_delay %in% NA))

fli |> filter(miss)


#2)
sum(is.na(flights$dep_time))

colSums(is.na(flights |> filter(is.na(dep_time))))
```

```{r}
library(lubridate)
head(flights)
```


```{r}
flights |> 
  mutate(datinha = as.Date(time_hour)) |> 
  summarize(
  voos_can = sum(is.na(dep_time)),
  voos_n_can = sum(!is.na(dep_time)),
  tot = n(),
  prop_cancelado = voos_can/voos_n_can,
  .by = c(datinha)
  )


```

