---
title: "R Notebook"
output: html_notebook
---


# 0.0 Imports

```{r}
renv::snapshot()
```

```{r}
options(scipen = 999)
options(digits = 6)
```


```{r}
library(tidyverse)
library(nycflights13)
```

# 1.0 Making Numbers


```{r}
x <- c("1.2", "1.5e2", "7.8")
parse_double(x)
```

```{r}
x <- c("$1,234", "R$ 3,456",  "506,503.24%")
parse_number(x)
```

# 2.0 Counts

```{r}
flights |> 
  group_by(tailnum) |> 
  summarize(miles = sum(distance))

flights |> count(tailnum, wt = distance)

```

```{r}
flights |> 
  group_by(dest) |> 
  summarize(n_cancelled = sum(is.na(dep_time)))
```

## 2.1 Exercises

```{r}
#1.0
flights |> count(is.na(dep_time))

#2.0
flights |>
  group_by(dest) |> 
  summarize(n = n()) |> 
  arrange(n)

flights |> 
  group_by(tailnum) |> 
  summarize(sum(distance))

```

# 3.0 Numeric Transformations

```{r}
x <- c(1, 2, 10, 20)
x * c(1, 2)

x * c(1, 2, 3)
```

```{r}
flights |> 
  filter(month == c(1, 2, 3))
```

```{r}
df <- tribble(
  ~x, ~y,
  1, 3,
  5, 2,
  7, NA,
)

df |> 
  mutate(min = pmin(x, y, na.rm = TRUE),
         max = pmax(x, y, na.rm = TRUE))


```

```{r}
head(flights)
```


```{r}
flights |> 
  mutate(
    hour = sched_dep_time %/% 100, 
    minute = sched_dep_time %% 100,
    .keep = "used"
  )

```


```{r}
flights |> 
  group_by(hour = sched_dep_time %/% 100) |> 
  summarize(prop_cancelled = mean(is.na(dep_time)), n = n()) |> 
  filter(hour > 1) |> 
  ggplot(aes(x = hour, y = prop_cancelled)) +
  geom_line(color = "grey50") +
  geom_point(aes(size = n))
  
```

```{r}
x <- 123.4568

round(x, 3)

round(x, 1)

round(x, -1)

round(x, -2)

floor(x)

ceiling(x/0.01) * 0.01


```


```{r}
x <- c(1, 2, 5, 10, 15, 20)
cut(x , breaks = c(0, 5, 10, 15, 20))

```

```{r}
x <- c(1, 2, 5, 10, 15, 20)
cut(x, breaks = c(0, 5, 10, 15, 20),
    labels = c("sm", "md", "lg0", "x1"))
```

```{r}
y <- c(NA, -10, 5, 10, 30)
cut(y, breaks = c(0, 5, 10, 15))


```

```{r}
#3)
flights |> 
  filter(month == 1, day == 1) |> 
  ggplot(aes(x = sched_dep_time, y = dep_delay)) +
  geom_point()

flights |> 
  mutate(frac_hours_sched = sched_dep_time %/% 100 + sched_dep_time %% 60,
         frac_hours_dep = dep_delay %/% 100 + dep_delay %% 60) |> 
  filter(month == 1, day == 1) |> 
    ggplot(aes( x = frac_hours_sched, y = frac_hours_dep)) +
    geom_point()
```

