---
title: "R Notebook"
output: html_notebook
---


# 0.0 Imports

```{r}
renv::restore()
```


```{r}
library(tidyverse)
library(nycflights13)
```


# 5.0 Case Study


```{r}
flights |>
  group_by(tailnum) |>
  summarise(delay = mean(arr_delay, na.rm = TRUE), n = n())
```


```{r}
flights |> filter(dest == "IAH") |> 
  group_by(year, month, day) |> 
  summarise(
    n     = n(),
    delay = mean(arr_delay, na.rm = TRUE)) |> 
  filter(n > 10)
```

```{r}
flights |> filter(
  carrier == "UA",
  dest   %in% c("IAH","HOU"),
  sched_dep_time > 0900,
  sched_arr_time < 2000
  ) |> 
  group_by(flight) |>
  summarize(
    delay     = mean(arr_delay, na.rm = TRUE),
    cancelled = sum(is.na(arr_delay)),
    n         = n()
    ) |> 
  filter(n > 10)
```




```{r}
flights |>
  filter(carrier == "UA", dest %in% c("IAH", "HOU"), sched_dep_time > 0900, sched_arr_time < 2000) |>
  group_by(flight) |>
  summarize(delay = mean(arr_delay, na.rm = TRUE), cancelled = sum(is.na(arr_delay)), n = n()) |>
  filter(n > 10)
```
