---
title: "R Notebook"
output: html_notebook
---


# 0.0 Imports

```{r}
renv::snapshot()
```



```{r}


library(scales)
library(tidyverse)
library(ggrepel)
library(patchwork)


```


# 1.0 Labels


```{r}
df <- tibble(
x = 1:10,
y = cumsum(x^2)
)
df
```

```{r}
ggplot(df, aes(x, y)) +
  geom_point() + 
  labs(
    x = quote(x[i]),
    x = quote(sum(x[i] ^ 2, i == 1, n))
  )
```

```{r}
ggplot(mpg, aes(x = cty, y = hwy)) +
  geom_point(aes(shape = drv, color = drv)) +
  labs( y = "Highway MPG",
        x = "City MPG",
        color = "Type of drive train",
        shape = "Type of drive train")
```

# 2.0 Annotation

```{r}
label_info <- mpg |> 
  group_by(drv) |> 
  arrange(desc(displ)) |> 
  slice_head(n = 1) |> 
  mutate(
    drive_type = case_when(
      drv == "f" ~ "front-wheel drive",
      drv == "r" ~ "rear-wheel drive",
      drv == "4" ~ "4-wheel drive"
    )
  ) |> 
  select(displ, hwy, drv, drive_type)
label_info
```


```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = drv)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) +
  geom_text(
    data = label_info,
    aes(x = displ, y = hwy, label = drive_type),
    fontface = "bold",
    size = 5,
    hjust = "right",
    vjust = "bottom"
  ) +
  theme(legend.position = "none")
```


```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = drv)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) +
  geom_label_repel(
    data = label_info,
    aes(x = displ, y = hwy, label = drive_type),
    fontface = "bold", size = 5, nudge_y = 2, nudge_x = 0
  ) +
  theme(legend.position = "none")
```



```{r}
potential_outliers <- mpg |>
  filter(hwy > 40 | (hwy > 20 & displ > 5))
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_text_repel(data = potential_outliers,
                  aes(label = model)) +
  geom_point(data = potential_outliers, color = "red") +
  geom_point(
    data = potential_outliers,
    color = "red",
    size = 4,
    shape = "circle open"
  )
```


```{r}
trend_text <- "Larger engine sizes tend to have lower fuel economy." |> 
  str_wrap(width = 30)
trend_text
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  annotate(
    geom = "label", x = 3.5, y = 38,
    label = trend_text,
    hjust = "left",
    color = "red") +
  annotate(
    geom = "segment",
    x = 3,
    y = 35,
    xend = 5,
    yend = 25,
    color = "red",
    arrow = arrow(type = "closed")
  )
```


## 2.1 Exercises


```{r}
#1)
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_text(aes(x = min(displ), y = max(hwy), label = "faq"),
            hjust = "center", vjust = "bottom") +
  geom_text(aes(x = min(displ), y = min(hwy), label = "feq")) +
  geom_text(aes(x = max(displ), y = max(hwy), label = "fiq")) +
  geom_text(aes(x = max(displ), y = min(hwy), label = "foq"))
```

```{r}
#2)
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  annotate(
    geom = "point",
    x = min(mpg$displ) + (max(mpg$displ) - min(mpg$displ))/2,
    y = min(mpg$hwy) + (max(mpg$hwy) - min(mpg$hwy))/2,
    size = 3,
    color = "red",
    shape = 1)
```


```{r}
#3)

dat_text <- tibble(
  label = c("du", "da"),
  cyl = c(4, 6)
)


ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_wrap(vars(cyl)) +
  geom_text(
    data = dat_text,
    aes(x = -Inf, y = -Inf, label = label),
    hjust = -0.1,
    vjust = -1
  )
```



```{r}
#4)
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_label(
    aes(x = -Inf, y = +Inf),
    hjust = "left",
    vjust = "top",
    label = "kéf",
    label.size = 2,
    label.padding = unit(1, "lines"),
    label.r = unit(2, "mm")
  )
```
```{r}
#5
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  geom_label(
    aes(x = -Inf, y = +Inf),
    hjust = "left",
    vjust = "top",
    label = "kéf",
    label.size = 2,
    label.padding = unit(1, "lines"),
    label.r = unit(2, "mm")
  ) +
  annotate(geom = "segment",
           x = 3,
           y = 35,
           xend = 5,
           yend = 25,
  arrow = arrow(
    angle = 25,
    length = unit(0.1 , "inches"),
    ends = "both",
    type = "closed"
  ))

```

#4.0 Scales

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = class))
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = class)) +
  scale_x_continuous() +
  scale_y_continuous() +
  scale_color_discrete()
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = class)) +
  scale_y_continuous(breaks = seq(15, 40, by = 5))
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = drv)) +
  geom_point() +
  scale_x_continuous(labels = NULL) +
  scale_y_continuous(labels = NULL) +
  scale_color_discrete(labels = c("4" = "4-wheel",
                                  "f" = "front",
                                  "r" = "rear"))
```

```{r}
ggplot(diamonds, aes(x = price, y = cut)) +
  geom_boxplot(alpha = 0.05) +
  scale_x_continuous(labels = label_dollar())
```
```{r}
ggplot(diamonds, aes(x = price, y = cut)) +
  geom_boxplot(alpha = 0.05) +
  scale_x_continuous(
    labels = label_dollar(
      scale = 1/1000,
      prefix = "R$",
      suffix = "Mil"
      ),
    breaks = seq(1000,
                 19000,
                 by = 6000
                 )
  )
```
```{r}
ggplot(diamonds, aes(x = cut, fill = clarity)) +
  geom_bar(position = "fill") +
  scale_y_continuous(name = "Percentage", labels = label_percent())
```

```{r}
presidential |> 
  mutate(
    id = 33 + row_number()) |> 
  ggplot(aes(x = start, y = id)) +
  geom_point() +
  geom_segment(aes(
    xend = end,
    yend = id
    )) +
  scale_x_date(
    name = "procecure",
    breaks = presidential$start,
    date_labels = "'%y",
    date_breaks = "5 years"
    )
```

```{r}
base <- ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = class))
  base + theme(legend.position = "right")
  base + theme(legend.position = "left")
  base + theme(legend.position = "top") +
    guides(col = guide_legend(nrow = 3))
  base + theme(legend.position = "bottom")


```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  theme(legend.position = "bottom") +
  guides(color = guide_legend(nrow = 2, override.aes = list(size = 4)))
  
```


```{r}
ggplot(diamonds,
       aes(x = carat, y = price)) +
  geom_bin2d()

ggplot(diamonds, aes(x = log10(carat), y = log10(price))) +
  geom_bin2d()
```



```{r}
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_bin2d() +
  scale_x_log10() +
  scale_y_log10()

```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = drv))

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = drv, shape = drv)) +
  scale_color_brewer(palette = "Spectral")
```

```{r}
presidential |> 
  mutate(id = 33 + row_number()) |> 
  ggplot(aes(x = start, y = id, color = party)) +
  geom_point() +
  geom_segment(aes(xend = end, yend = id)) +
  scale_color_manual(values = c(Republican = "#E81B23",
                                Democratic = "#00AEF3"))
```

```{r}
df <- tibble(
x = rnorm(10000),
y = rnorm(10000)
)

ggplot(df, aes(x, y)) +
  geom_hex() +
  coord_fixed() +
  labs(title = "Default continuous")

ggplot(df, aes(x, y)) +
  geom_hex() +
  coord_fixed() +
  scale_fill_viridis_c() +
  labs(title = "Viridi Conti")

ggplot(df, aes(x, y)) +
  geom_hex() +
  coord_fixed() +
  scale_fill_viridis_b() +
  labs(title = "Viridi Conti")

```

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = drv)) +
  geom_smooth() +
  scale_x_continuous(limits = c(5, 6)) +
  scale_y_continuous(limits = c(10,25))

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = drv)) +
  geom_smooth() +
  coord_cartesian(xlim = c(5, 6), ylim = c(10,25))
```

```{r}
x_scale <- scale_x_continuous(limits = range(mpg$displ))
y_scale <- scale_y_continuous(limits = range(mpg$hwy))
col_scale <- scale_color_discrete(limits = unique(mpg$drv))
```

```{r}

suv <- mpg |> filter(class == "suv")
compact <- mpg |> filter(class == "compact")

# Left
ggplot(suv, aes(x = displ, y = hwy, color = drv)) +
  geom_point() +
  x_scale +
  y_scale +
  col_scale
# Right
ggplot(compact, aes(x = displ, y = hwy, color = drv)) +
  geom_point() +
  x_scale +
  y_scale +
  col_scale
```


## 4.1 Exercises

```{r}
#1)
df <- tibble(
x = rnorm(10000),
y = rnorm(10000)
)

ggplot(df, aes(x, y)) +
  geom_hex() +
  scale_fill_gradient() +
  coord_fixed()

#Because the wrong aesthetic was passed
```

```{r}
#3)
head(presidential)

ggplot(presidential |> 
         mutate(
           id = 33 + row_number()), aes(
             x = start,
             y = id)) +
  geom_label_repel(aes(label = name),nudge_y=1) +
  annotate(geom = "label",
           label = "cresceu tudo KKKKKKK",
            x = as.Date("1960-01-01"), 
            y = 42.5,
          ) +
  annotate(geom = "segment",
           x = as.Date("1960-01-01"), xend = as.Date("1980-01-01"),
           y = 42.5, yend = 42.5,
           color = "purple",
           arrow = arrow(type="closed")) +
  geom_point(aes(color = party)) +
  scale_color_manual(values = c(Republican = "#E81B23",
                                Democratic = "#00AEF3")) +
  scale_x_date(
    date_breaks = "4 years",
    date_labels = "%y")
  
```

```{r}
head(presidential)
```


