---
title: "R Notebook"
output: html_notebook
---


# 0.0 Imports

```{r}
renv::restore()
```




```{r}
library(nycflights13)
library(tidyverse)
```


```{r}
df0 <- data.frame(flights)
glimpse(df0)
```

# 1.0 Rows


```{r}
df0 %>% 
  filter(dep_delay > 120) %>%  glimpse
```

```{r}
flights %>% 
  filter(month ==1 & day ==1)
```

```{r}
flights %>% 
  filter(month %in% c(1,2)) %>% glimpse
```
```{r}
flights %>% 
  arrange(desc(dep_delay))
```

```{r}
flights %>% 
  distinct()
```

```{r}
flights %>% 
  distinct(origin, dest)
```

```{r}
flights %>% 
  distinct(origin, dest, .keep_all = TRUE)
```
```{r}
flights %>% 
  count(origin, dest, sort = TRUE)
```

```{r}
flights %>%  glimpse
```

```{r}
flights %>% glimpse
```


```{r}
flights %>% 
  filter(arr_delay >= 2 & 
           dest %in% c("IAH","HOU") &
           carrier %in% c("UA", "AA") &
           dep_delay <= 0 &
           month %in% c(7,8,9) &
           air_time >= 30
  )
           
        
  
```

```{r}
flights %>% arrange(desc(dep_delay))

```

```{r}
flights %>% arrange(time_hour)
```

```{r}
flights %>% filter(air_time == min(flights$air_time, na.rm = TRUE))
```

```{r}
flights %>% filter(year == 2013) %>% distinct(month, day) %>% count()
```

```{r}
flights %>% filter(distance == max(flights$distance, na.rm=TRUE)) %>% distinct(origin)
flights %>% filter(distance == min(flights$distance, na.rm=TRUE)) %>% distinct(origin)
```
```{r}
# Doesn't matter because there's no aggregation before the filter.
```


# 2.0 Columns

```{r}
flights %>% 
  mutate(gain = dep_delay - arr_delay,
         speed = distance / air_time * 60, .after = day, .keep = "used")
```

```{r}
flights %>% 
  select(year:day)

flights %>% 
  select(!year:day)

flights %>% 
  select(where(is.character))

flights %>% 
  select(starts_with("ori"))

flights %>% 
  select(ends_with("gin"))

flights %>% 
  select(contains("ig"))

flights %>% 
  select(num_range("x", 1:3))

flights %>% 
  relocate(time_hour, air_time )

flights %>% 
  relocate(year:dep_time, .after = time_hour)

flights %>% 
  select(dep_time, sched_dep_time, dep_delay)

flights %>% 
  select(starts_with("dep") | starts_with("arr"))

flights %>% 
  select(ends_with("time") | ends_with("delay"))

flights %>% 
  select(contains("time"))


# Just appears once
flights %>% 
  select(dep_time, dep_time)

variables <- c("year", "month", "day", "dep_delay",
"arr_delay","fonfon")

flights %>% 
  select(all_of(variables))

# The function any_of might be helpful when I want to select columns without caring if one of them is missing. On the other hand all_of assert that all columns needs to be selected, otherwise a error is thrown.


flights %>% select(contains("TIME", ignore.case = FALSE))

flights %>% rename(air_time_min = air_time) %>% relocate( air_time_min, .before=1)

flights %>% 
  select(tailnum) %>%
  arrange(tailnum)

```

# 3.0 The Pipe

The Native Pipe is better because it's minimalist, it's available all time (since it's native) and also allowed te base R to jettison infrequently used features.

# 4.0 Groups

```{r}
flights |> 
  group_by(month) |> 
  summarize(
    avg_delay = mean(dep_delay, na.rm=TRUE),
    count_delay = n()
  )

flights |> 
  group_by(dest) |> 
  slice_max(arr_delay, n = 2, with_ties = FALSE) |> 
  relocate(dest, arr_delay)

daily <- flights |> 
  group_by(year, month, day)

daily

daily_flights <- daily |> 
  summarize( n = n(), .groups="keep") |> 
  ungroup()

daily_flights

flights |> 
  summarize(
    delay = mean(dep_delay, na.rm=TRUE),
    n = n(),
    .by = c(year, month)
  )
```

