---
title: "R Notebook"
output: html_notebook
---


# 0.0 Imports



```{r}
library(tidyverse)
library(tidymodels)
library(nycflights13)
tidymodels_prefer()
```

# 1.0 Workflow Basics

```{r}
lm_model <- 
  linear_reg() |> 
  set_engine("lm")

lm_wflow <- 
  workflow() |> 
  add_model(lm_model) |> 
  add_formula(Sale_Price ~ Longitude + Latitude)
```


```{r}
lm_fit <-  fit(lm_wflow, ames_train)
```


```{r}
lm_fit
```

```{r}
predict(lm_fit, ames_test |> slice(1:3))
```
```{r}
lm_fit |> update_formula(Sale_Price ~ Longitude)
```

```{r}
lm_wflow <- 
  lm_wflow |> 
  remove_formula() |> 
  remove_variables() |> 
  add_variables(outcome = Sale_Price, predictors = c(ends_with("tude")))
lm_wflow
```

```{r}
fit(lm_wflow, ames_train)
```

# 2.0 Creating Multiple Workflows at Once

```{r}
final_lm_res <- last_fit(lm_wflow, ames_split)
final_lm_res
```


```{r}
final_lm_res$.workflow
```



```{r}
fitted_lm_wflow <- extract_workflow(final_lm_res)

collect_metrics(final_lm_res)
collect_predictions(final_lm_res) |> slice(1:5)
```

# Summary

```{r}

```

