---
title: "R Notebook"
output: html_notebook
---


# 0.0 Imports



```{r}
library(tidyverse)
library(tidymodels)
ames1 <- data(ames, package = "modeldata")
tidymodels_prefer()
```

# 1.0 Commom Methods for Splitting Data

```{r}
set.seed(502)


ames_split <-  initial_split(
  ames,
  prop = 0.80,
  strata = Sale_Price
  )
ames_split
```


```{r}
ames_train <-  training(ames_split)
ames_test <-  testing(ames_split)

dim(ames_train)
```


CHAPTER 6


# 1.0 Create a Model

```{r}
linear_reg() |> 
  set_engine("lm") |> 
  translate()
```

```{r}
lm_model <- 
  linear_reg() |> 
  set_engine("lm")
```


```{r}
lm_form_fit <- 
  lm_model |>
  fit(Sale_Price ~ Longitude + Latitude, data = ames_train)
```


```{r}
lm_xy_fit <- 
  lm_model |> 
  fit_xy(
    x = ames_train |> select(Longitude, Latitude),
    y = ames_train |> pull(Sale_Price)
  )

lm_form_fit
```

```{r}
lm_xy_fitw
```

```{r}
?rand_forest
rand_forest(trees = 1000, min_n = 5) |> 
  set_engine("ranger") |> 
  set_mode("regression") |> 
  translate()
```


```{r}
?rand_forest
rand_forest(trees = 1000, min_n = 5) |> 
  set_engine("ranger", verbose = TRUE) |> 
  set_mode("regression") |> 
  translate()
```

# 2.0 Use the Model Results

```{r}
lm_form_fit |> extract_fit_engine()
```

```{r}
lm_form_fit |> extract_fit_engine() |> vcov()
```


```{r}
class(lm_form_fit)
class(lm_form_fit$fit)
```

```{r}
model_res <- 
  lm_form_fit |> 
  extract_fit_engine() |> 
  summary()
model_res
```

```{r}
param_est <- coef(model_res)
class(param_est)

param_est
```


```{r}
tidy(lm_form_fit)
```

# 3.0 Make Predictions


```{r}
ames_test_small <- ames_test |> slice(1:5)
predict(lm_form_fit,
        new_data = ames_test_small)
```

```{r}
ames_test_small |> 
  select(Sale_Price) |> 
  bind_cols(predict(lm_form_fit, ames_test_small)) |> 
  bind_cols(predict(lm_form_fit, ames_test_small, type = "pred_int"))
```

```{r}
tree_model <- 
  decision_tree(min_n = 2) |> 
  set_engine("rpart") |> 
  set_mode("regression")
```


```{r}
tree_fit <- 
  tree_model |> 
  fit(
    Sale_Price ~ 
      Longitude +
      Latitude,
    data = ames_train)
```


```{r}
ames_test_small |> 
  select(Sale_Price) |> 
  bind_cols(predict(tree_fit, ames_test_small))
```


