---
title: "R Notebook"
output: html_notebook
---


# 0.0 Imports



```{r}
library(tidyverse)
library(tidymodels)
library(nycflights13)
tidymodels_prefer()
options(scipen=999)
```

# 1.0 Asimple recipe hor Ames Housing Data

```{r}
set.seed(502)
ames_split <- initial_split(ames, prop = 0.80, strata =
Sale_Price)
ames_train <- training(ames_split)
ames_test <- testing(ames_split)
```


```{r}
simple_ames <-
recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built +
Bldg_Type,
data = ames_train) %>%
step_log(Gr_Liv_Area, base = 10) %>%
step_dummy(all_nominal_predictors())

lm_model <- linear_reg() %>% set_engine("lm")

lm_wflow <-
workflow() %>%
add_model(lm_model) %>%
add_variables(outcome = Sale_Price, predictors = c(Longitude,
Latitude))

lm_wflow <-
lm_wflow %>%
remove_variables() %>%
add_recipe(simple_ames)
lm_wflow

lm_fit <- fit(lm_wflow, ames_train)
#> ══ Workflow
```


```{r}
rf_model <- 
  rand_forest(trees = 1000) |> 
  set_engine("ranger") |> 
  set_mode("regression")

rf_wflow <- 
  workflow() |> 
  add_formula(
  Sale_Price ~ 
  Neighborhood + 
  Gr_Liv_Area + 
  Year_Built + 
  Bldg_Type + 
  Latitude + 
  Longitude) |> 
  add_model(rf_model)

rf_fit <- rf_wflow |> 
  fit(data = ames_train)
```


```{r}
estimate_perf <- function(model, dat) {
# Capture the names of the `model` and `dat` objects
  cl <- match.call()
  obj_name <- as.character(cl$model)
  data_name <- as.character(cl$dat)
  data_name <- gsub("ames_", "", data_name)

reg_metrics <- metric_set(rmse, rsq)

model %>%
  predict(dat) %>%
  bind_cols(dat %>% select(Sale_Price)) %>%
  reg_metrics(Sale_Price, .pred) %>%
  select(-.estimator) %>%
  mutate(object = obj_name, data = data_name)
}
```

```{r}
estimate_perf(lm_fit, ames_train)
```

```{r}
estimate_perf(rf_fit, ames_train)
```

```{r}
estimate_perf(rf_fit, ames_test)
```

```{r}
estimate_perf(lm_fit, ames_test)
```
# 1.0 Resampling methods

## 1.1 Cross-Validation


```{r}
set.seed(1001)
ames_folds <- vfold_cv(ames_train, v = 10)
ames_folds
```

```{r}
ames_folds$splits[[1]] |> analysis() |> dim()
```

## 1.2 Repeated Cross-Validation

```{r}

erro_padrão = desvio_padrao/raizquadrada(N)

vfold_cv(ames_train, v = 10, repeats= 5)
```

## 1.3 Leave-One-Out Cross-Validation


## 1.4 Monte Carlo Cross-Validation


```{r}
mc_cv(ames_train,
      times = 20)
```

